$DEVELOPER_LANGUAGES = ['Ruby', 'Ruby on Rails', 'Java', 'JavaScript', 'jQuery', 'PHP', 'Python', 'C#', 'C++', 'Vue', 'React', 'React Native', 'Solidity', 'Rust', 'Go', 'Solidity', 'Swift', 'Dart', 'Kotlin', 'Perl', 'Scala']
$DEVELOPER_ROLE_TYPES = ['fulltime', 'parttime', 'remote', 'onsite']
$DEVELOPER_ROLE_LEVELS = ['junior', 'midlevel', 'senior']
$DEVELOPER_SEARCH_STATUSES = ['is_active', 'unavailable', 'invisible']
$DEVELOPER_COUNTRY_AREAS = ['København', 'Århus', 'Odense', 'Fyn', 'Nordjylland', 'Midtjylland', 'Sydjylland', 'Andet', 'Udlandet']